### ISSUE TITLE
vendor dir missing

### ISSUE THREAD

**Issue by jerrywham** [kriss/mvvm#1]
autoloader.php includes 'vendor/autoload.php' but vendor dir is missing. Where can we find it ?

**Comment by tontof** [comment]
I've just modified the autoload to work without vendor by default
https://github.com/KrISS/mvvm/commit/49c1858d53b35fee297f4e96499bf3f494aa3c3a

vendor should be created by composer : https://getcomposer.org/
when installed, just run : ```composer install``` or ```./composer.phar install``` depending on how you've installed it and it should add all vendors that can be used with KrISS MVVM thanks to the ```composer.json``` file

**Comment by jerrywham** [comment]
Ok. Cool. It works.
